# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['mygame.py'],
    pathex=[],
    binaries=[],
    datas=[('C:/Users/Kirill/Desktop/Game/Game2/img/chicken.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/dildo1.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/dildo2', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/heart', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/laser.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/player.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/potato.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/shit.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/starfield.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion00.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion01.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion02.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion03.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion04.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion05.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion06.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion07.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/img/regularExplosion08.png', 'img'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/expl1.wav', 'snd'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/expl2.wav', 'snd'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/main.mp3', 'snd'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/meow1.wav', 'snd'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/meow2.wav', 'snd'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/meow3.wav', 'snd'),
    ('C:/Users/Kirill/Desktop/Game/Game2/snd/pew.wav', 'snd'),
    ('font.ttf', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mygame',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
